@startuml credit-cards

	!include theme.iuml

	Title Credit Cards

	start

	repeat
		fork
			:spend;
		fork again
			:due date>
		end fork
		:cash back;
		note right: cash back program
		:pay in full;

	repeat while () -> build\ncredit

	end

	!include footer.iuml

@enduml