@startuml single-family

!include theme.iuml


start
:ClickServlet.handleRequest();
:new page;


/'jumba'/


if (Page.onSecurityCheck) then (true)
  :Page.onInit();
  if (isForward?) then (no)
	:Process controls;
	if (continue processing?) then (no)
	  stop
	endif
	
	if (isPost?) then (yes)
	  [[http://plantuml.com]]:Page.onPost(); /'hyperlinks work in svg!'/
	else (no)
	  :Page.onGet();
	endif
	:Page.onRender();
  endif
else (false)
endif


'*hjkhjk*/
if (do redirect?) then (yes)
  :redirect process;
else
  if (do forward?) then (yes)
	:Forward request;
  else (no)
	:Render page template;
  endif
endif

stop

@enduml
