@startuml Theme

skinparam {
  /'backgroundColor Gainsboro'/
  BorderColor Red
  PathHoverColor Blue
}

skinparam Title {
  FontColor Navy
  BackgroundColor PaleGoldenRod
  BorderColor Navy
  BorderRoundCorner 20
  FontSize 24
}

skinparam activity {
  BackgroundColor Ivory
  BorderColor CornflowerBlue
  BorderThickness 1
  FontColor DimGray
  

  Arrow {
    Color dimgray
    FontColor dimgray
  }

  Start {
    Color PHYSICAL
  }

  End {
    Color Coral
  }

  Diamond {
    BackgroundColor Ivory
    BorderColor CornflowerBlue
    FontColor DarkGray
  }

  BackgroundColor<< Exception >> Red
	BorderColor<< Exception >> White
}

skinparam Swimlane {
  BorderColor CornflowerBlue 
}

skinparam Partition {
  BackgroundColor Ivory
  BorderColor CornflowerBlue
  BorderThickness 1
  FontColor CornflowerBlue
  FontSize 16
  BorderRoundCorner 20
}

skinparam Note {
  BackgroundColor LightSteelBlue
  BorderColor CornflowerBlue
  FontColor White
}

skinparam Legend {
  BackgroundColor LightSteelBlue
  BorderColor CornflowerBlue
  FontColor White
}

skinparam Footer {
  FontColor Navy
}

@enduml