@startuml Theme

skinparam {
  /'backgroundColor Gainsboro'/
  BorderColor Red
  PathHoverColor Blue
}

skinparam Title {
  FontColor Navy
  BackgroundColor PaleGoldenRod
  BorderColor Navy
  BorderRoundCorner 20
}

skinparam activity {
  BackgroundColor Ivory
  BorderColor CornflowerBlue
  FontColor DarkGray
  

  Arrow {
    Color dimgray
    FontColor dimgray
  }

  Start {
    Color Navy
  }

  End {
    Color Red
  }

  Diamond {
    BackgroundColor Ivory
    BorderColor CornflowerBlue
    FontColor DarkGray
  }

  BackgroundColor<< Exception >> Red
	BorderColor<< Exception >> White
}

skinparam Swimlane {
  BorderColor CornflowerBlue 
}

skinparam Partition {
  BackgroundColor DarkSeaGreen
  BorderColor CornflowerBlue
  BorderThickness 1
  FontColor White
  FontSize 16
}
skinparam Note {
  BackgroundColor LightSteelBlue
  BorderColor CornflowerBlue
  FontColor White
}

skinparam Footer {
  FontColor Navy
}

@enduml