@startuml car

	!include theme.iuml

	!include header.iuml

	Title Car

	start

	if(rental income > car payment) then (no)
		stop
	endif


	if(< 3 years old) then (yes)
		stop
	endif

	:finance thru credit union;

	end

	!include footer.iuml

@enduml