@startuml financial-freedom-program

	!include theme.iuml

	!include header.iuml

	Title Financial Freedom Program\n(FFP)

	start

	#PHYSICAL:<&dollar> 500]

	repeat
		->paid;
		:active;
		fork
			:2-day\nfinancial freedom seminars;
		fork again
			[[https://www.lifestyleshub.com]]#LightSkyBlue:<&globe> lifestyles hub\n----\ncalendar\ndocuments;
		fork again
			[[https://ffp-lifestylesunlimited.bridgeapp.com]]#LightSkyBlue:<&globe> bridge\n----\ncalendar\ndocuments;
		fork again
		[[http://www.lifestylesunlimited.com/category/radio_shows]]#LightSkyBlue:<&globe> radio shows;
		fork again
			:special events;
		fork again
			:case studies;
		fork again
			[[http://wealthandpassiveincomeexpo.com]]#LightSkyBlue:<&globe> annual\nwealth and passive\nincome expo\npromo code EXPOEVENT;
		fork again
			:member services
			----
			<i><&clock> M-F 9-5
			<i><&phone> 972-8270208;
		fork again
			[[https://luincvendor.com]]#LightSkyBlue:<&globe> vendor program;
		fork again
			#PHYSICAL:<&dollar> tax write-off]
		fork again
			:<&clock> 1 year>
		end fork

		:inactive;

		#PHYSICAL:<&dollar> 200]
	repeat while ()
	

	!include footer.iuml

@enduml