@startuml index

	!include theme.iuml

	!include header.iuml

	Title Unlimited Lifestyle

	start

		repeat

			fork
				partition learning {
					repeat
						fork
							:watch video;
						fork again
							:attend event;
						fork again
							:member services Q&A;
						end fork
						:document process;
					repeat while ()
				}
			fork again
				[[../single-family/pre-qualification.svg?sanitize=true]]#LightSkyBlue:pre-qualification;

			fork again
				[[../single-family/team-building.svg?sanitize=true]]#LightSkyBlue:build team;
			fork again
				[[credit-cards.svg?sanitize=true]]#LightSkyBlue:build credit;
			fork again
				partition saving {
					repeat
						:work;
						:paycheck;
						fork
							:save >= 60% of earnings\n<i>2% interest;
						fork again
							:live off <= 40% of earnings;
							floating note left:<i>act your wage
						end fork

					repeat while (have money for deal)
					->yes;
				}
			end fork
			[[legal.svg?sanitize=true]]#LightSkyBlue:structure legal;
			if(have > 50,000) then (yes)
				[[../multi-family/multi-family-deal.svg?sanitize=true]]#LightSkyBlue:do (another)\nmulti-family deal;
			else (no)
				[[../single-family/single-family-deal.svg?sanitize=true]]#LightSkyBlue:do (another)\nsingle-family deal;
				note right
					||City||All In||
					|Dallas|40k|
					|Houston|??k|
					|San Antonio|??k|
				end note
			endif
			:refine process;
		repeat while (can live off passive income)
		->yes;
		:quit job;

		[[taxes.svg?sanitize=true]]#LightSkyBlue:pay taxes;


	end

	!include footer.iuml

@enduml