@startuml taxes

	!include theme.iuml

	!include header.iuml

	Title Taxes

	start

	note right
		property = land + improvements
	end note

	:depreciate improvements;
	note right
		passive income - depreciation expense
		write off against income
		25,000 cap, or carry forward
		to other years
	end note
	
	:become real estate professional;
	note right
		ex: owner / operator
		removes tax limitation
		must work ____ hrs / week
		cost segregation
	end note

	:sell property;
	note right
		can target multiple
		target - within 45 days
		close again - within 180 days
		sale price + $1
	end note

	:1031 Tax Free Exchange]
	note right
		tax deferral

	end note

	:die;
	note right
		kids pay no tax
		stepped up basis
	end note
	end

	!include footer.iuml

@enduml