@startuml index

	!include theme.iuml

	!include header.iuml

	Title Multi Family

	fork
		[[multi-family-deal.svg?sanitize=true]]#LightSkyBlue:Multi Family Deal;
	fork again
		[[preferred-investor-group-program.svg?sanitize=true]]#LightSkyBlue:Preferred Investor Group Program;
	fork again
		[[lead-investor-program.svg?sanitize=true]]#LightSkyBlue:Lead Investor Program;
	end fork


	!include footer.iuml

@enduml