@startuml index

	!include theme.iuml

	!include header.iuml

	Title Multi Family

	fork
		' [[single-family-deal.svg?sanitize=true]]:Single Family Deal;
	fork again
		' [[challenge-program.svg?sanitize=true]]:Challenge Program;
	end fork


	!include footer.iuml

@enduml