@startuml index

	!include theme.iuml

	!include header.iuml

	Title Multi Family

	fork
		[[preferred-investor-group-program.svg?sanitize=true]]#LightSkyBlue:Preferred Investor Group Program;
	fork again
		' [[challenge-program.svg?sanitize=true]]#LightSkyBlue:Challenge Program;
	end fork


	!include footer.iuml

@enduml