@startuml preferred-investor-group-program

	!include theme.iuml

	!include header.iuml

	Title Preferred Investor Group (PIG)\nEducation & Mentoring Program\n(Single-Family and/or  Multi-Family)

	start

	#PHYSICAL:<&dollar> Commitment Fee 18,000]
	if(challenge member) then (yes)
		#PHYSICAL:<&dollar> Challenge Refund (7,000)]
	else (no)
	endif

	repeat
		->paid;
		:active;
		fork
			[[../single-family/challenge-program.svg?sanitize=true]]#LightSkyBlue:challenge program\nbenefits;
		fork again
			:personalized\nplanning session;
		fork again
			:multi-family\n1-on-1 consulting;
		fork again
			:multi-family\nrealtors;
		fork again
			:multi-family\nroad trips;
		fork again
			:multi-family\nspecialized education]
		fork again
			:multi-family\noperator consultant;
		fork again
			:preferred investor\nnetworking events;
		fork again
		:<&clock> 1 year>
		end fork
		:inactive;

		#PHYSICAL:<&dollar> Annual Renewal 3,000]
	repeat while (<&loop>)

	!include footer.iuml

@enduml