@startuml advertising

	!include theme.iuml

	!include header.iuml

	Title Advertising

	start

	-><&timer> wait until property funds\n& in contract;
	
	partition Preparation {
		fork
			:<&phone> get google voice number
			----
			don't want people having your personal number;
		fork again
			:<&envelope-closed> get inquiry email
			----
			<i>address@gmail.com;
		fork again
			:<&envelope-closed> get application email
			----
			<i>address_apps@gmail.com;
		fork again
			:<&cloud> get paypal account;
			:<&envelope-closed> paypal email address
			----
			<i>property@paypal.com;
		fork again
			:<&cloud> get youtube account;
			:<&rss> get youtube channel
			----
			<&user> <i>user name: property;
			:<&video> upload property tour video;
		end fork

		:set up the inquiry email
		<i>auto-respond message
		<i>this is like a website
		----
		<&envelope-open> reply-to: address_apps@gmail.com
		----
		<&pencil> thank you message
		<&pencil> online ad content
		<&magnifying-glass> criteria
		<&image> floor plan
		<&image> pictures
		<&map> map
		<&video> <color:cornflowerblue> youtube tour video
		<&dollar> paypal payment instructions
		----
		<&paperclip> application
		<&paperclip> credit / criminal permission from
		;
		note right
			how to set up
			====
			# Gmail -> Settings -> Advanced
			  turn on canned responses
			# Compose email as shown here
			# ⁞ on bottom menu -> Canned responses -> 
			  Save draft as template -> property name
			# Settings -> Filters -> Create new filter
			# filter action -> Send canned response -> property name
		end note
	}

	partition "House Preparation" {
		fork
			:open all blinds;
		fork again
			:unlock gates;
		end fork
	}

	partition Advertising {
		fork
			:put info in window
			====
			* pictures of rooms
			** front
			** bath
			** kitchen
			** living
			* amenities
			* crime for area
			* application criteria
			;
		fork again
			#Magenta:sign in front yard
			<i>neon pink from walmart
			<i>written with a sharpie
			<i>90% of leases come from this
			====
			| 3-2-2 | $875 |
			| 1680 sq ft | ready 4/1/2019 |
			| All New Blah | All New Blah |
			| (214) 555-1212 | call Fred |
			| property@gmail.com||
			]
		fork again
			:online add
			====
			* location large (area of town)
			* location small (subdivision)
			* size
			* amenities
			* date available
			* repairs
			  <i>"to be complete before move-in"
			* rent amount
			* address
			* phone, email, name
			]
			fork 
				:newspaper;
			fork again
				[[https://dallas.craigslist.org]]#LightSkyBlue:<&globe> craig's list;
			fork again
				[[https://postless.com]]#LightSkyBlue:<&globe> postless;
			fork again
				[[https://cozy.co]]#LightSkyBlue:<&globe> cozy;
			fork again
				:outgoing phone message;
			end fork
		end fork
	}

	partition "Process Applicants" {
		repeat
			:* (re)check price
			* (re)check cleanliness
			* (re)check functionality;
			fork
				[[leasing.svg?sanitize=true]]#LightSkyBlue:lease\n====\n<&people> <i>first come, first served;
			fork again
				-><&timer> wait for a tour demand;
				:schedule tour date
				----
				application required;
				:give tour to next group of applicants;
			fork again
				:<&timer> one week>
			end fork
		repeat while (leased)->no
	}



	!include footer.iuml

@enduml