@startuml challenge-program

	!include theme.iuml

	!include header.iuml

	Title Challenge Program (Single Family)

	start

	#PHYSICAL:<&dollar> 7000]

	repeat
		->paid;
		:active;
		fork
			[[../unlimited-lifestyle/financial-freedom-program.svg?sanitize=true]]#LightSkyBlue:financial freedom program;
		fork again
			:mentors;
		fork again
			:1-on-1 consulting;
		fork again
			:Lifestyles realtors;
		fork again
			:email blasts;
		fork again
			:road trips;
		fork again
			:specialized education classes;

		fork again
			:1 year>
		end fork
		:inactive;

		#PHYSICAL:<&dollar> 2000]
	repeat while ()


	!include footer.iuml

@enduml