@startuml challenge-program

	!include theme.iuml

	!include header.iuml

	Title Challenge Education & Mentoring Program\n(Single Family)

	start

	#PHYSICAL:<&dollar> Enrollment Fee 7,000]

	repeat
		->paid;
		:active;
		fork
			[[../unlimited-lifestyle/financial-freedom-program.svg?sanitize=true]]#LightSkyBlue:financial freedom program;
		fork again
			:mentors;
		fork again
			:1-on-1 consulting;
		fork again
			:Lifestyles realtors;
		fork again
			:<&email> email blast;
			:<&email> reply for package;
			:package]
		fork again
			:road trips
			----
			<i>may include vendors;

		fork again
			:specialized education classes;

		fork again
			:1 year>
		end fork
		:inactive;

		#PHYSICAL:<&dollar> Annual Renewal 2,000]
	repeat while ()

	legend 
		ready to buy program
		
		for new members
		mentors find deal just for you
		goal: get 1st property <= 30 days
	end legend


	!include footer.iuml

@enduml