@startuml closing

	!include theme.iuml

	!include header.iuml

	Title Closing

	start

		fork
			:Fannie Mae Purchase
			Money Mortgage
			====
			75-80%;
		fork again
			:Hard Money Loan
			Private Money Mortgage
			====
			70-75% ARV
			====
			6-16.5% Interest;
		end fork

		if(used agent(s)) then (yes)
			:seller pays all
			RE commission;
		endif

	end

	!include footer.iuml

@enduml