@startuml evicting

	!include theme.iuml

	!include header.iuml

	Title Evicting

	start
	partition "Violation" {
		fork
			:fail to pay rent;
		fork again
			:surpise pet;
		fork again
			:straw person;
		end fork
	}
	
	:obtain proof of violation;

	partition "Notice of Eviction" {
		note left: see document hub for more details
		if(rent is late) then (yes)
			fork
				#PHYSICAL:<&dollar> late fees\n----\n50 + 10 / day]
			fork again
				#PHYSICAL:<&dollar> pet fine\n----\n100/pet/day]
			fork again
				[[https://drive.google.com/open?id=0B18-6Qbo-LJ5Y3d0V1VBeGRHWlE]]#LightSkyBlue:Texas Notice To Vacate - Failure to Pay Rent]
			end fork
		else (no)
			[[https://drive.google.com/open?id=0B18-6Qbo-LJ5U2pkTXRaMTg3SjQ]]#LightSkyBlue:notice to vacate\n----\n<i>eviction notice]
		endif
	}
	
	fork
		:tenant moves out;
	fork again
		:<&timer> 3 days>
	end fork

	if(vacates on time) then (no)

		partition "Filing a Eviction Suit" {
			fork
				:Summons]
			fork again
				:Complaint]
			fork again
				#PHYSICAL:<&dollar> filing fee <&arrow-thick-right> 200]
			end fork
		}

		-><&timer> court date;	

		partition "Eviction Hearing" {
			if(shows up) then(no)
			else (yes)
				:evidence]
				:present evidence;
				if(late rent) then(no)
					if(judge rules in my favor) then (no)
						:judgement in tenant's favor]
						#LightPink:now what?;
						stop
					else (yes)
					endif
				else (yes)
					if(tenant has all late rent) then(yes)
						:do not accept late rent;
					else (no)
						:do not accept mediation;
					endif
				endif
			endif
			:judgement in my favor]
		}

		fork
			:tenant moves out;
		fork again
			:<&timer> 7 days>
		end fork

		if(vacates on time) then (no)
			partition "Enforce Eviction" {
				fork
					:Writ of Possession]
				fork again
					#PHYSICAL:<&dollar> fee <&arrow-thick-right> 150-200]	
				end fork
				:notice]
				:sheriff delivers notice;
			}
			fork
				:tenant moves out;
			fork again
				:<&timer> 24 hours>
			end fork
			if(vacates on time) then (no)
				partition "Physical Eviction" {
					fork
						-><&people> occupants;
						:sheriff enforces eviction;
					fork again
						-><&home> property;
						if(sheriff says it's trash) then (no)
							:movers move to curb;
							fork 
								:tenant retrieves property;
							fork again
								:<&timer> 24 hours>
								:dispose of property;
							end fork
						else (yes)
							:<&trash> movers to the trash;
						endif
					end fork
				}
			else (yes)
			endif
		else (yes)
		endif
	else (yes)
	endif
	:change locks;
	end

	!include footer.iuml

@enduml