@startuml finding

	!include theme.iuml

	!include header.iuml

	Title Finding

	start

	partition Finding {
		fork
			
			partition "find it myself\ntakes a great deal of time\ndoes not leverage other people's time, money and knowledge" {
				fork
					[[http://realestate.sabor.com]]#LightSkyBlue:<&globe> sabor.com;
				fork again
					[[http://har.com]]#LightSkyBlue:<&globe> har.com;
				fork again
					[[http://www.real-estate-byowner.com]]#LightSkyBlue:<&globe> real-estate-byowner.com;
				fork again
					[[http://www.realtor.com]]#LightSkyBlue:<&globe> realtor.com;
				fork again
					[[http://www.erealty.com]]#LightSkyBlue:<&globe> erealty.com;
				fork again
					[[http://www.redfin.com]]#LightSkyBlue:<&globe> redfin.com;
				fork again
					[[http://www.hubzu.com]]#LightSkyBlue:<&globe> hubzu.com;
				fork again
					[[https://www.postbankruptcyreport.com]]#LightSkyBlue:<&globe> courthouse leads;
				fork again
					:go to courthouse
					----
					get lists of foreclosures;
				fork again
					:add name on REO lists
					----
					real estate they own;
				fork again
					:drive thru neighborhoods
					----
					distressed property / owner:
					* overgrown lawn
					* newspapers stacked up
					* damaged siding
					* damaged roof
					* broken window;
				fork again
					:farming
					----
					put flyers on door handles;
				fork again
					:direct mailing
					----
					post cards / flyers;
				fork again
					:put up signs
					----
					<i>"I buy houses";
				end fork
			}

		fork again
			[[https://app.lifestylesquest.com]]#LightSkyBlue:quest;

		fork again
			[[listing-agents.svg?sanitize=true]]#LightSkyBlue:use listing agents;
		fork again
			:wholesaler
			----
			no license
			----
			experienced investor only
			buyer beware -
			will get you
			upside down;
		fork again
			:other investors
			----
			networking;
		fork again
			fork
				[[challenge-program.svg?sanitize=true]]#LightSkyBlue:challenge program;
			fork again
				[[../multi-family/preferred-investor-group-program.svg?sanitize=true]]#LightSkyBlue:preferred investor program;
			end fork
			fork
				:email blast;
				:reply for package;
				:package]
			fork again
				[[https://www.har.com/lifestyles-realty-dallas-inc/broker_NTREIS-LIRE01]]#LightSkyBlue:lifestyles realty\n----\nalready-analyzed\noff-MLS deals;
			end fork
		end fork
	}

	partition Filtering {
		if(correct status\n----\nactive\nactive option\nnew\nback on market\nprice change) then(no)
			stop
		else (yes)
			note right
				sold?
			end note
		endif

		if(correct housing type\n----\nsingle family detached) then(no)
			note right
				if you can't buy all of it
				don't buy any of it
			end note
			stop
		else (yes)
		endif

		if(recent listing\n----\n <= 60 days) then(no)
			note right
				something is wrong with it
				everyone has already picked over them
			end note
			stop
		else (yes)
		endif

		if(correct rooms\n----\n3-2-2\n4-2-2) then(no)
			note right: costs too much to fix
			stop
		else (yes)
		endif

		if(correct size\n----\n1000-2000 sq ft) then(no)
			stop
		else (yes / lower rehab)
		endif
		

		if(correct age\n----\n1983 - current) then(no)
			note right
				lead paint
				old pipes
				old electric
			end note
			stop
		else (yes)
		endif

		if(correct neighborhood\n----\nnot scary\nuse google street view) then(no)
			note right
				high crime area
				run search w/o filters
				to get the big picture
			end note
			stop
		else (yes)
		endif

		if(correct price\n----\n$80-160k) then(no)
			note right
				amount of mortgage vs
				amount of rent
			end note
			stop
		else (yes)
		endif

		if(correct $/sq ft\n----\n$10-$85/sq ft) then(no)
			note right
				amount of mortgage vs
				amount of rent
			end note
			stop
		else (yes)
		endif

		if(correct class\n----\nmiddle) then(no)
			note right
				don't buy low end
			end note
			stop
		else (yes)
		endif

	}

		partition "Comparative Market Analysis (CMA)\nSales Comparison\n<i>Find >= 3 Similar Homes" {

			if(close by\n----\nsame sub-division) then(no)
				stop
			else (yes)
			endif

			if(listed recently\n----\nwithin 3-9 months) then(no)
				stop
			else (yes)
			endif

			if(similar size\n----\n± 300 square feet) then(no)
				stop
			else (yes)
			endif

			if(sale prices\n----\n>> higher than this property) then(no)
				note right
					price ≠ value
					<i>"no meat on the bone"
					>= 25% higher
				end note
				stop
			else (yes)
			endif
		}

		partition "Comparative Market Analysis (CMA)\nRent Comparison\n<i>Find >= 1 Similar Homes" {

		}


	end

	!include footer.iuml

@enduml