@startuml leasing

	!include theme.iuml

	!include header.iuml

	Title Leasing

	start

  partition "Take Application" {
    #PHYSICAL:<&dollar> application fee 50]
    :NTN search $15;
    :NTN report]
    note right
      call NTN for process
    end note
    repeat
      fork 
        :application]
      fork again
        :checking statement]
      fork again
        if(self-employed) then (no)
          fork
            :W2]
          fork again
            :paycheck stubs
            ====
            how far back]
          end fork
        else (yes)
          fork 
            :bank statements
            ----
            2 years]
          fork again
            :tax returns
            ----
            2 years]
          end fork
        endif
      fork again
        #LightPink:not acceptable
        ====
        <&ban> employer letters
        <&ban> undocumented child support
        <&ban> social security]
      end fork
      note right: all occupants > 18
    repeat while (application(s) 100% complete)->return to\napplicant
    ->yes;
  }

  partition Pre-Screening {
    if(is lawyer) then(yes)
      (R)
      stop
    elseif(friend / relative) then(yes)
      (R)
      stop
    elseif(tax returns profitable) then(no)
      (R)
      stop
    elseif(income > 3 x rent) then(no)
      (R)
      stop
    elseif(years employed < 2) then(no)
      (R)
      stop
    elseif(is middle class) then(no)
      (R)
      stop
    elseif(exotic pet) then(yes)
      (R)
      stop
    elseif(pet > 35 lbs) then(yes)
      (R)
      stop
    elseif(vicious breed pet) then(yes)
      (R)
      stop
    endif
  }  

  partition "Categorize Applicants" {
    if(live with parents) then(yes)
      #Plum:purple;
    elseif(age 18-19) then(yes)
      #Plum:purple;
    elseif(evicted) then(yes)
      #Plum:purple;
    elseif(no history) then(yes)
      #Plum:purple;
    elseif(wad of cash) then(yes)
      #Plum:purple
      ====
      <i>illicit business;
    elseif(has checking account) then(no)
      #Pink:pink;
    else
      #80FF80:green;
    endif
  }

  partition "Rental History Check" {
    :verify owner of previous address
    ----
    not current;
    :call previous owner;
    
    if(recommends) then(no)
      (R)
    endif
    ->yes;
  }

  partition "Employment Check" {
    if(employee) then (yes)
      :verification call;
    endif
  }

  partition "Criminal Background Check" {
    :pull criminal;
    if(violent / drugs) then(yes)
      (R)
    endif
    if(warrents) then(yes)
      #Plum:purple;
    endif
  }

  partition "Credit Check" {
    :pull credit;
    if(credit score >= 650) then (yes)
      #80FF80:green;
    elseif(credit score >= 550) then (yes)
      #Pink:pink;
    elseif(credit score >= 500) then (yes)
      #Plum:purple;
    else (no)
      (R)
      stop
    endif

  }

  partition "Pet Addendum" {
    if(application says has pet)
      :pet interview;
      if(dog or cat) then(no)
        stop
      elseif(> 35 pounds)
        stop
      elseif(vicious breed)
        stop
      else
        :$200 / pet fee;
        note right: non-refundable
        :$200 / pet deposit;
        note right: refundable
        :$25 / mo / pet pet rent;
      endif
    else (fish, or no pets)
      :inform $100/pet/day violation
      ----
      regardless of stay or owner
      ----
      small caged pets? (hamsters, turtles);
    endif
  }

  partition "Signing" {
    fork
      [[https://drive.google.com/open?id=0B18-6Qbo-LJ5aVB6VXY4c0JiTms]]#LightSkyBlue:<&pencil> lease]
    fork again
      #PHYSICAL:<&dollar> pet fees]
    fork again
      #PHYSICAL:<&dollar> deposit
      ----
      <&check> money order
      <&check> cashier's check
      <&ban> cash
      <&ban> check]
      #80FF80:if(<color:dimgrey>green) then(yes)
        #80FF80:collect 1x rent;
      #Pink:elseif(<color:dimgrey>pink) then(yes)
        :rejection letter]
        #Pink:collect 2x rent
        ----
        <i>Credit Restoration Program;
        note right
          not recommended
        end note 
      #Plum:elseif(<color:dimgrey>purple) then(yes)
        :rejection letter]
        #Plum:collect 3x rent
        ----
        only if your background is
        * law enforcement
        * combat
        * "raised in the hood";
      endif
    end fork
  }
  -><&timer> wait until move in date;

  partition "Move In Date" {
    if(moving in) then (yes)
      #PHYSICAL:<&dollar> rent]
      note right: pro-rated?
      :<&key> give key;
    else (changed mind)
      #PHYSICAL:<&dollar> refund <&arrow-thick-right> ]
      note right: how much?
      stop
    endif
  }
  [[single-family-deal.svg?sanitize=true]]#LightSkyBlue:manage property;
  stop

  partition Rejection {
    (R)
    :rejection letter]
    :deliver rejection
    ----
    via email;
  }

  legend right
    | color | tenant type |Notes|
    |<#80FF80> green |<#80FF80> perfect ||
    |<#Pink> pink |<#Pink> blemished |more risky|
    |<#Plum> purple |<#Plum> risky tenant |will trash property|
  endlegend  


	!include footer.iuml

@enduml