@startuml negotiating

	!include theme.iuml

	!include header.iuml

	Title Negotiating

	start

	:make offer
	----
	buy low;

	:pre-qualifification letter <&arrow-thick-right> ]

	:<&arrow-thick-right> contract]

	end

	!include footer.iuml

@enduml