@startuml pre-qualification

	!include theme.iuml

	!include header.iuml

	Title Pre-Qualification

	start

  if(  debt / income >= 45%) then(yes)
    stop
  endif
  
  if(self-employed) then (yes)
    if(2 years profit tax returns) then(no)
      stop
    endif
  elseif(years employed > 2) then(no)
    stop
  endif
  
  if(credit score > 620) then(no)
    stop
  endif
  if(bankruptcy < 4 years) then(yes)
    stop
  endif
  if(foreclosure < 7 years) then(yes)
    stop
  endif
  if(short sale / deed-in-lieu < 4 years) then(yes)
    stop
  endif
  if(late mortgage payment < 12 months) then(yes)
    stop
  endif


  :apply;

  :Qualification Letter/

  end

  legend
    Terms
    | ARV | after repair value |
  end legend

	!include footer.iuml

@enduml