@startuml pre-qualification

	!include theme.iuml

	!include header.iuml

	Title Pre-Qualification

	start

  fork

    partition Conventional {

      if(  debt / income <= 50%) then(no)
        stop
      endif
      
      if(self-employed) then (yes)
        if(2 years profit tax returns) then(no)
          stop
        endif
      elseif(years employed > 2) then(no)
        stop
      endif
      
      if(credit score > 650) then(no)
        stop
      endif
      if(bankruptcy < 4 years) then(yes)
        stop
      endif
      if(foreclosure < 7 years) then(yes)
        stop
      endif
      if(short sale / deed-in-lieu < 4 years) then(yes)
        stop
      endif
      if(late mortgage payment < 12 months) then(yes)
        stop
      endif

    }

  fork again
    partition "Fannie Mae Purchase Money Mortgage" {
      if(house in perfect condition) then (no)
        stop
      endif
      :75-80% lending out}
    }
    
  fork again
    partition "Hard Money Loan" {
      :70% ARV}
      note right: don't do 75%\nuntil refi
      :6-16.5% interest}
      :2-4 month term}
      :closes in 3 days}
    }

  fork again
    partition "Rate and Term Refinance Loan" {
      :75%}
      #Plum:no more out of pocket?;
    }

  fork again
    partition "Delayed Financing" {
      #Plum:offer cash?;
      :75-80% of all in cost}
      :get all money back minus repairs}
    }

  fork again
    partition "Cash Out Refinance Loan" {
      if(6-12 months of "seasoning"\n====\n(being rented out)) then (no)
        stop
      endif
      :pull out 75% of appraised value}
    }
  end fork

  :apply;

  :Qualification Letter/

  end

  legend
    Terms
    | ARV | after repair value |
  end legend

	!include footer.iuml

@enduml