@startuml rehabbing

	!include theme.iuml

	!include header.iuml

	Title Rehabbing (Repairing / Make Ready)

	start

		:take photos of all work
		----
		* advertising
		* proof of condition;
	end

	!include footer.iuml

@enduml