@startuml selling

	!include theme.iuml

	!include header.iuml

	Title Selling

	start

	if(selling to tenant)
		#PHYSICAL:<&dollar> realtor fee 0]
		note right: how?
	else
	endif

	

	end

	!include footer.iuml

@enduml