@startuml single-family-deal

	!include theme.iuml

	!include header.iuml

	Title Single Family Deal

	start

	[[finding.svg?sanitize=true]]#LightSkyBlue:find;
	:compare;
	[[evaluating.svg?sanitize=true]]#LightSkyBlue:analyse;
	:visit;
	[[negotiating.svg?sanitize=true]]#LightSkyBlue:contract;
	[[due-diligence.svg?sanitize=true]]#LightSkyBlue:inspect;
	[[closing.svg?sanitize=true]]#LightSkyBlue:close;
	fork
		repeat
			fork
				[[rehabbing.svg?sanitize=true]]#LightSkyBlue:rehab;
			fork again
			  [[advertise.svg?sanitize=true]]#LightSkyBlue:advertise;
				[[leasing.svg?sanitize=true]]#LightSkyBlue:lease;
			end fork
			-> move in;
			fork
				:maintain;
			fork again
				repeat
					-><&timer>\nrent due;
					:collect rent;
				repeat while(rent paid?)->yes
				->no;
				[[evict.svg?sanitize=true]]#LightSkyBlue:evict;
			end fork
			-> move out;
		repeat while(keep?)->yes
		->no;
	fork again
		:1-3 years>
	end fork
	[[selling.svg?sanitize=true]]#LightSkyBlue:sell;
	end

	!include footer.iuml

@enduml