@startuml team-building

	!include theme.iuml

	!include header.iuml

	Title Build Team

	start

	repeat

		:choose;

		fork
			:mentor;
		fork again
			:lenders;
		fork again
			:real estate agents / brokers
			----
			20 of them;
		fork again
			:home inspectors
			----
			licensed only;
		fork again
			:insurance agents;
		fork again
			:general contractor;
		fork again
			:roofer;
		fork again
			:foundation specialist;
		fork again
			:termite inspector;
		fork again
			:property management
			----
			out of town deals;
		fork again
			:tenant screening company
			----
			NTN $15 & charge $50;
		fork again
			:attorney
			----
			real estate expert;
		fork again
			:cpa
			----
			real estate expert;
		fork again
			:business checking
			----
			can get free;
		end fork
	repeat while (primary and two alternates)
	#PHYSICAL:team ready;
	

	!include footer.iuml

@enduml