@startuml index

	!include theme.iuml

	Title Home

	fork
		[[unlimited-lifestyle/index.svg?sanitize=true]]#LightSkyBlue:Unlimited Lifestyle;
	fork again
		[[single-family/index.svg?sanitize=true]]#LightSkyBlue:Single Family;
	fork again
		[[multi-family/index.svg?sanitize=true]]#LightSkyBlue:Multi Family;
	end fork


	!include footer.iuml

@enduml